version: "3"
services:
  db:
    image: mongo:4.2
    container_name: mongo
  app:
    build:
      context: .
    image: rayleun1/koala
    container_name: koala
    ports:
      - "3000:5000"
    env_file:
      - .env