default: &default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: koala_development

test:
  <<: *default
  database: koala_test

production:
  <<: *default
  adapter: postgresql
  host: db
  username: postgres
  password: